# Generated by Django 3.2.6 on 2021-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addredd',
            new_name='address',
        ),
    ]
